# Generated by Django 5.2 on 2025-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('cimage', models.CharField(max_length=255)),
                ('datas', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
