# Generated by Django 5.2 on 2025-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_type_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cimage',
        ),
        migrations.AddField(
            model_name='customer',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
