# Generated by Django 5.2 on 2025-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_cimage_customer_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
