# Generated by Django 5.2 on 2025-05-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('postproduct', '0001_initial'),
        ('salesman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('SenderName', models.TextField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.PositiveSmallIntegerField()),
                ('RecieverId', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='salesman.salesman')),
                ('SenderId', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.customer')),
                ('wrokId', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='postproduct.postproduct')),
            ],
        ),
    ]
