# Generated by Django 5.2 on 2025-05-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='wrokId',
            new_name='ItemId',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='rate',
        ),
        migrations.AlterField(
            model_name='notification',
            name='SenderName',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
