# Generated by Django 5.2 on 2025-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_wrokid_notification_itemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('alert', 'Alert'), ('remainder', 'Remainder'), ('update', 'Update')], default='message', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('hight', 'High')], default='medium', max_length=50),
        ),
    ]
