# Generated by Django 5.2 on 2025-08-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='pimages/')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='fashions', max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_telegram', models.URLField(blank=True, null=True)),
                ('contact_tick', models.URLField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pimages/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.product')),
            ],
        ),
    ]
