# Generated by Django 5.2 on 2025-05-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pro', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('image', models.TextField(blank=True, default='')),
                ('type', models.CharField(default='2', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customer.customer')),
            ],
        ),
    ]
