# Generated by Django 5.2 on 2025-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
