# Generated by Django 5.2 on 2025-05-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postproduct', '0002_alter_postproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproduct',
            old_name='empname',
            new_name='postername',
        ),
    ]
