# Generated by Django 5.2 on 2025-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postproduct', '0004_alter_postproduct_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='type',
            field=models.CharField(default='3', max_length=10, null=True),
        ),
    ]
