# Generated by Django 5.2 on 2025-05-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postproduct', '0005_alter_postproduct_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproduct',
            old_name='description',
            new_name='ion',
        ),
    ]
