# Generated by Django 5.2 on 2025-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_salesman_type_alter_salesman_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
