# Generated by Django 5.2 on 2025-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0003_salesman_pimage_alter_salesman_cimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='id',
        ),
        migrations.AddField(
            model_name='salesman',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
