# Generated by Django 5.2 on 2025-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0004_remove_salesman_id_salesman_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='Id',
        ),
        migrations.AddField(
            model_name='salesman',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
