# Generated by Django 5.2 on 2025-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='category',
            field=models.CharField(default='electronics', max_length=100),
        ),
    ]
