# Generated by Django 5.2 on 2025-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
