# Generated by Django 5.2 on 2025-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_first_name_product_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
