# Generated by Django 5.2 on 2025-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_tick',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='fashions', max_length=100),
        ),
    ]
