# Generated by Django 5.2 on 2025-08-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_contact_tick_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
    ]
