# Generated by Django 5.2 on 2025-08-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_name',
        ),
    ]
