# Generated by Django 5.2 on 2025-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_category_remove_product_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact_tick',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='fashions', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
