# Generated by Django 5.2 on 2025-08-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_contact_tick_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
