# Generated by Django 5.2 on 2025-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_tick',
            field=models.URLField(blank=True, null=True),
        ),
    ]
