# Generated by Django 5.2 on 2025-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_contact_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('fashions', 'Fashions'), ('electronics', 'Electronics'), ('homes', 'Homes'), ('carbrands', 'Car Brands'), ('foods', 'Foods & Beverages'), ('appliances', 'Home & Appliances'), ('health', 'Health & Beauties'), ('events', 'Events & Weddings'), ('entertainments', 'Intertainments'), ('travels', 'Travels'), ('daily', 'Daily Discounts'), ('weekly', 'Weekly Discounts'), ('new', 'New Advantages'), ('newoffers', 'New Offers'), ('upcomming', 'Upcomming Services'), ('repair', 'Repair & Maintainance'), ('agricultureal', 'Agriculture & Livestock'), ('books', 'Books & Stationary'), ('toys', 'Toys & Games'), ('jewelry', 'Jewelries'), ('insurances', 'Finance & Insurances'), ('baby', 'Baby & Kids products'), ('pet', 'Pet Suplies & services'), ('green', 'Green & Eco-friendly products'), ('medical', 'Medical & Pharmaceuticals'), ('logistic', 'logistic & Delivery Services'), ('consustancy', 'Legal & Consultancy Services'), ('cleaning', 'Cleaning & Sanitation Services'), ('telecom', 'Telecomunication Services'), ('art', 'Art & Handicrafts'), ('photograpy', 'Photograpy & Videograph'), ('design', 'Furniture & Interior Design'), ('fitness', 'Fitness & Sports Service'), ('software', 'Software & IT services'), ('sercurity', 'Security Services'), ('printing', 'Printing & publishing'), ('automotive', 'Automotive Services'), ('waste', 'Waste Management & Recycling '), ('Human', 'Human Resources & staffing'), ('energy', 'Energy & Utilities'), ('gaming', 'Gaming & eSports'), ('tatue', 'Tatto And Piercing Studios'), ('nursing', 'Elderly Care & Nursing Services'), ('rental', 'Rental Services'), ('decor', 'Event Planning & Decor'), ('translation', 'Language And Translation'), ('nonprofit', 'Non Profit & Charity Organization'), ('freight', 'Courier & Freight Services'), ('Beauty', 'Beauty Sallons and Barbershops'), ('music', 'Music & Instruments'), ('office', 'Coworking & Office Spaces'), ('digital', 'Digital Marketing Services'), ('architecture', 'Architecture & Engineering Services'), ('mental', 'Mental Health & Wellness Services'), ('homesecurity', 'Home Securty & Smart Homes'), ('land', 'Land Escaping and Gardeing services'), ('podcasting', 'podcasting & Audio Production'), ('stionary', 'Stationary & Office Supplieis'), ('marin', 'Marine & boating Services'), ('virtual', 'Virtual Events and Webinars'), ('funding', 'Croud Funding And Investment Services'), ('elearing', 'Elearning & online Cources'), ('carwash', 'Car Wash & Detailing'), ('admin', 'Virtual Assistant & Admin Support')], max_length=50, null=True),
        ),
    ]
