# Generated by Django 5.2 on 2025-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
