# Generated by Django 5.2 on 2025-08-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_category_alter_product_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
