# Generated by Django 5.2 on 2025-09-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='verified',
        ),
    ]
