# Generated by Django 5.2 on 2025-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('ended', ' Ended'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%')], default='ended', max_length=20),
        ),
    ]
