# Generated by Django 5.2 on 2025-09-09 08:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
