# Generated by Django 5.2 on 2025-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('ended', ' Ended'), ('waiting', 'Waiting'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%')], default='waiting', max_length=20),
        ),
    ]
