# Generated by Django 5.2 on 2025-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days this discount will stay active', null=True),
        ),
    ]
