# Generated by Django 5.2 on 2025-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_discount_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_start_date',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days this discount will stay active', null=True),
        ),
    ]
