# Generated by Django 5.2 on 2025-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_start_date',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days left discount to begin', null=True),
        ),
    ]
