# Generated by Django 5.2 on 2025-11-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_discount_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('coming', 'Coming')], default='waiting', max_length=20),
        ),
    ]
