# Generated by Django 5.2 on 2025-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('waiting', 'Waiting For Discount'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('coming', 'Coming Soon')], default='waiting', max_length=20),
        ),
    ]
