# Generated by Django 5.2 on 2025-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('waiting', 'Waiting For Discount'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('coming', 'Coming Soon'), ('open', 'We are open'), ('prize', 'For prize'), ('student', 'For Students'), ('teacher', 'For Teachers')], default='waiting', max_length=20),
        ),
    ]
