# Generated by Django 5.2 on 2025-12-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_tips',
            field=models.CharField(choices=[('only_discount', 'Only discount'), ('coming', 'Coming Soon'), ('open', 'We are open'), ('prize', 'For prize'), ('bonus', 'Bonus'), ('dubie', 'Dubie')], default='only_discount', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='for_whom',
            field=models.CharField(choices=[('everybody', 'Every body'), ('teachers', 'For Teachers'), ('students', 'For Students'), ('teenagers', 'For Teenagers'), ('elders', 'For Elders'), ('disables', 'For Disables'), ('special', 'For Special Needs'), ('holyday', 'For Holyday')], default='everybody', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'Men Fashions'), ('banks', 'Banks'), ('women', 'Women Fashions'), ('homes', 'Homes'), ('carbrands', 'Car Brands'), ('foods', 'Foods & Beverages'), ('appliances', 'Home & Appliances'), ('health', 'Health & Beauties'), ('events', 'Events & Weddings'), ('entertainments', 'Intertainments'), ('travels', 'Travels'), ('daily', 'Daily Discounts'), ('weekly', 'Weekly Discounts'), ('new', 'New Advantages'), ('newoffers', 'New Offers'), ('upcommings', 'Upcomming Services'), ('repair', 'Repair & Maintainance'), ('agricultural', 'Agriculture & Livestock'), ('books', 'Books & Stationary'), ('toys', 'Toys & Games'), ('jewelry', 'Jewelries'), ('insurances', 'Finance & Insurances'), ('baby', 'Baby & Kids products'), ('pet', 'Pet Suplies & services'), ('green', 'Green & Eco-friendly products'), ('medical', 'Medical & Pharmaceuticals'), ('logistic', 'logistic & Delivery Services'), ('consultancy', 'Legal & Consultancy Services'), ('cleaning', 'Cleaning & Sanitation Services'), ('telecom', 'Telecomunication Services'), ('art', 'Art & Handicrafts'), ('photograpy', 'Photograpy & Videograph'), ('design', 'Furniture & Interior Design'), ('fitness', 'Fitness & Sports Service'), ('software', 'Software & IT services'), ('security', 'Security Services'), ('printing', 'Printing & publishing'), ('automotive', 'Automotive Services'), ('waste', 'Waste Management & Recycling '), ('human', 'Human Resources & staffing'), ('energy', 'Energy & Utilities'), ('gaming', 'Gaming & eSports'), ('women_fashions', 'Tatto And Piercing Studios'), ('nursing', 'Elderly Care & Nursing Services'), ('rental', 'Rental Services'), ('decor', 'Event Planning & Decor'), ('holyday', 'Holyday Discounts'), ('translation', 'Language And Translation'), ('nonprofit', 'Non Profit & Charity Organization'), ('freight', 'Courier & Freight Services'), ('sallons', 'Beauty Sallons and Barbershops'), ('music', 'Music & Instruments'), ('office', 'Coworking & Office Spaces'), ('digital', 'Digital Marketing Services'), ('architecture', 'Architecture & Engineering Services'), ('mental', 'Mental Health & Wellness Services'), ('homesecurity', 'Home Securty & Smart Homes'), ('land', 'Land Escaping and Gardeing services'), ('podcasting', 'podcasting & Audio Production'), ('stationary', 'Stationary & Office Supplieis'), ('marin', 'Marine & boating Services'), ('virtual', 'Virtual Events and Webinars'), ('funding', 'Croud Funding And Investment Services'), ('elearning', 'Elearning & online Cources'), ('carwash', 'Car Wash & Detailing'), ('admin', 'Virtual Assistant & Admin Support')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(choices=[('waiting', 'Waiting For Discount'), ('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%')], default='waiting', max_length=20),
        ),
    ]
