# Generated by Django 5.2 on 2026-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_additional_tips_product_for_whom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_tips',
            field=models.CharField(choices=[('only_discount', 'Only discount'), ('coming', 'Coming Soon'), ('open', 'We are open'), ('sale', 'For Sale'), ('rent', 'For rent'), ('prize', 'For prize'), ('bonus', 'Bonus'), ('dubie', 'Dubie'), ('giveaway', 'For Give Away'), ('Equb', 'For Equb'), ('exchange', 'For Echange')], default='only_discount', max_length=20),
        ),
    ]
